require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - interage-helpers.gemspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - bin/**/*
    - vendor/**/*
    - lib/generators/interage/helpers/*/templates/**/*.rb
